### ISSUE TITLE
Clean up job retrieval code - possible errors

### ISSUE THREAD

**Issue by JimCircadian** [JimCircadian/model-ensembler#25]
Appears there is a situation whereby the JobName can be empty. This code is a bit nasty as it is, so make it far more defensive and account for this possibility fields might be missing when traversing the list from scontrol.

```
Traceback (most recent call last):
  File "/data/hpcdata/users/chll1/WAVI_Julia/WAVIhpc/venv/lib/python3.7/site-packages/model_ensembler/batcher.py", line 264, in run_batch_item
    job = await cluster.find_id(job_id)
  File "/data/hpcdata/users/chll1/WAVI_Julia/WAVIhpc/venv/lib/python3.7/site-packages/model_ensembler/cluster/slurm.py", line 46, in find_id
    if v.split("=")[0] == "JobName"][0],
IndexError: list index out of range
[12-02-22 00:21:00    :WARNING ] - Command returned err: None
[12-02-22 00:21:00    :ERROR   ] - Job status for run PIGTHW5km_constant_melt_runs-14 retrieval whilst slurm running, waiting and retrying
Traceback (most recent call last):
  File "/data/hpcdata/users/chll1/WAVI_Julia/WAVIhpc/venv/lib/python3.7/site-packages/model_ensembler/batcher.py", line 264, in run_batch_item
    job = await cluster.find_id(job_id)
  File "/data/hpcdata/users/chll1/WAVI_Julia/WAVIhpc/venv/lib/python3.7/site-packages/model_ensembler/cluster/slurm.py", line 46, in find_id
    if v.split("=")[0] == "JobName"][0],
```

**Comment by JimCircadian** [comment]
This was fixed by #20
